version: '3'

services:

  web:
    build: .

    volumes:
      - .:/patent
      - /data/media:/patent/media
      - /data/db/db.sqlite3:/patent/db.sqlite3
    
    command: bash -c "python3 manage.py collectstatic --noinput --clear  && yes | python3 manage.py migrate && uwsgi --ini /patent/config/uwsgi.ini && sleep infinity"
    ports:
      - "81:81"

    networks:
      web_net:
        ipv4_address: 172.19.0.2
      
    tty: true
    stdin_open: true 

  proxy:
    image: nginx:1.17

    depends_on: 
      - "web"

    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - /cert:/cert
    environment:
      - NGINX_PORT=8000
    ports:
      - "443:443"
      - "8000:8000"
      - "80:80"
      - "8080:8080"
    restart: always
    networks:
      web_net:
        ipv4_address: 172.19.0.3

networks:
  web_net:
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.1/24"