# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='UNKNOWN', max_length=400)),
                ('summary', models.CharField(max_length=4000, null=True)),
                ('file', models.FileField(upload_to=gallery.models.Photo.content_file_name)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
