# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 02:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180824_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-uploaded_at',)},
        ),
        migrations.AlterField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 8, 26, 2, 0, 7, 297591, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
