# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_photo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='exif',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
