# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_photo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='author',
            field=models.CharField(default='Y WEN', max_length=400),
        ),
        migrations.AlterField(
            model_name='photo',
            name='summary',
            field=models.TextField(max_length=4000, null=True),
        ),
    ]
