# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20180829_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
