# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180828_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Y WEN', max_length=200),
        ),
    ]
