# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 03:30
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover_by',
            field=models.FileField(default='Anonymous', upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.FileField(null=True, upload_to=blog.models.Blog.content_file_name),
        ),
    ]
