# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180907_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_by',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
